[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[logger]
hideWelcomeMessage = true

[theme]
base = "dark"
primaryColor = "#7C3AED"
backgroundColor = "#151530"
secondaryBackgroundColor = "#1E1E3E"
textColor = "#E2E8F0"
font = "sans serif"
